/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_secmem_remoteroid_universal_natives_FrameHandlerU */

#ifndef _Included_org_secmem_remoteroid_universal_natives_FrameHandlerU
#define _Included_org_secmem_remoteroid_universal_natives_FrameHandlerU
#ifdef __cplusplus
extern "C" {
#endif
#undef org_secmem_remoteroid_universal_natives_FrameHandlerU_BYTE_PER_PIXEL
#define org_secmem_remoteroid_universal_natives_FrameHandlerU_BYTE_PER_PIXEL 4L
/*
 * Class:     org_secmem_remoteroid_universal_natives_FrameHandlerU
 * Method:    getFrameBuffer
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_org_secmem_remoteroid_universal_natives_FrameHandlerU_getFrameBuffer
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
