/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_secmem_remoteroid_natives_FrameHandler */

#ifndef _Included_org_secmem_remoteroid_natives_FrameHandler
#define _Included_org_secmem_remoteroid_natives_FrameHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_secmem_remoteroid_natives_FrameHandler
 * Method:    getFrameBuffer
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_org_secmem_remoteroid_natives_FrameHandler_getFrameBuffer
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
